### ISSUE TITLE
autocomplete repeats the first letter

### ISSUE THREAD

**Issue by malkarouri** [supercoderz/redis_kernel#2]
Using the command:

    ipython console --kernel redis

when I write the letter ```g``` and press TAB I get the following suggestions

    ggetrange ggetbit   ggetset   gget

and autocomplete to ```gget```, which naturally responds with "ERR unknown command 'gget'" if I press enter.

**Comment by hari-allamraju** [comment]
I have fixed the issue and created a new 0.4 version on pypi - please check and let me know if you see any other issues

**Comment by malkarouri** [comment]
Thanks for the quick turnaround. Unfortunately, I get a long error ending with:
```
C:\Users\Muhammad Alkarouri\Anaconda\envs\py3k\lib\site-packages\redis_kernel\kernel.py in start_history(self=<redis_kernel.kernel.RedisKernel object>)
     80
     81     def start_history(self):
---> 82         db_name = HISTORY_DB or DEFAULT_DB_NAME
        db_name = undefined
        global HISTORY_DB = undefined
        global DEFAULT_DB_NAME = 'history.db'
     83         try:
     84             self.history_db  = sqlite3.connect(db_name)

NameError: name 'HISTORY_DB' is not defined
```

As far as I can see, it is because the file ```redis_kernel\kernel.py``` either expects a ```redis_kernel_config``` to define the variables or if not found defines HOST and PORT to None but not HISTORY_DB.

Adding line 26 in ```redis_kernel\kernel.py```:
        HISTORY_DB = None

makes it work, with the bug above resolved.

Sorry for not preparing a proper patch. Keep up the good work.

**Comment by hari-allamraju** [comment]
I will take a look at this tonight

**Comment by hari-allamraju** [comment]
Fixed and updated pypi - haven't been updating this for a while and missed the silly bits; let me know if this breaks anything. I will be able to look at things on the weekend again

**Comment by malkarouri** [comment]
Installed redis_kernel from pypi. Version 0.5. Using `pip install redis_kernel --user`.

Bug fixed. Everything works successfully as far as I can see.
