### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by marmalodak** [supercoderz/redis_kernel#3]
Whether this is my bug or an ipython issue, or a redis_kernel issue, I'm not sure.  My ipython notebook works well enough, but I'm seeing this pop up:

    Notebook validation failed
    The save operation succeeded, but the notebook does not appear to be valid. The validation error was:
    Notebook Validation failed: 'name' is a required property:
    {}

FWIW, this is the notebook metadata:

    {
      "kernelspec": {
        "name": "redis",
        "display_name": "Redis",
        "language": "redis"
      },
      "language_info": {}
    }

And this is my kernel.json:

    {
        "display_name":    "Redis",
        "language":        "redis"
        "argv":            ["/e2e/ipython3-venv/bin/python3.4", "-m", "redis_kernel", "-f", "{connection_file}"],
        "codemirror_mode": "shell",
    }

**Comment by hari-allamraju** [comment]
This could be due to the newer version of ipython. I haven't had a chance to look at this yet. 

Will try for the weekend , but if you want to make a pull request then please go ahead

**Comment by hari-allamraju** [comment]
I have updated the code with the language info that will resolve this issue. Can you please install using the repo and check if it works? If it all works fine then I will do a release

**Comment by marmalodak** [comment]
Thanks for the update.

I did this: `pip install  'git+https://github.com/supercoderz/redis_kernel.git#egg=redis_kernel'`  Since I'm using jupyter instead of ipython, how do I make this kernel available to my jupyterhub?

**Comment by hari-allamraju** [comment]
I have done a release and uploaded a version 0.5.1 to pypi - so you can uninstall the version you installed from github and install with the standard 'pip install redis_kernel' command

**Comment by marmalodak** [comment]
I don't think this is the same issue, but I rebuilt my jupyter virtual
python environment and then `pip install redis_kernel`.  Jupyter starts up
well, but as soon as I try to create a new `redis` notebook, I see this:

    ...
    [I 2015-05-28 12:14:24.105 root handlers:172] Creating new notebook in
    [I 2015-05-28 12:14:26.176 root kernelmanager:85] Kernel started:
0f001d04-bd5a-4e04-b89c-e8d2ee2c9629
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File
"/e2e/venv/jupyter-git-venv/lib64/python3.4/site-packages/redis_kernel/__main__.py",
line 1, in <module>
        from kernel import *
    ImportError: No module named 'kernel'
    [I 2015-05-28 12:14:29.173 root restarter:103] KernelRestarter:
restarting kernel (1/5)
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/runpy.py", line 170, in _run_module_as_main
        "__main__", mod_spec)
      File "/usr/lib64/python3.4/runpy.py", line 85, in _run_code
        exec(code, run_globals)
      File
"/e2e/venv/jupyter-git-venv/lib64/python3.4/site-packages/redis_kernel/__main__.py",
line 1, in <module>
        from kernel import *
    ImportError: No module named 'kernel'

Which module is it looking for?

**Comment by hari-allamraju** [comment]
Which Python version are you using? It seems I might have broken the Python 3 version - will look at this tonight

**Comment by marmalodak** [comment]
i'm using Python3.  In case it matters, I'm trying to use this with
https://github.com/jupyter.

**Comment by hari-allamraju** [comment]
Please uninstall and install the package again. It should work this time. I accidentally broke a part of the code that is not covered in the unit tests and so could not catch this.

Sorry for the multiple iterations.

**Comment by hari-allamraju** [comment]
Hello, if the last update fixed your issue, can you please mark this as closed?

**Comment by marmalodak** [comment]
I'll try to get to this before the end of the weekend.

**Comment by marmalodak** [comment]
I just did an installation and I'm looking for the `kernel.json` file.  I didn't find one. Should it not be there?

    (ipython3-venv) [root@dyn40-21-140 venv]# pip uninstall redis_kernel
    Uninstalling redis-kernel-0.5.2:
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel-0.5.2-py3.4.egg-info
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__init__.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__main__.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/__init__.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/__main__.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/constants.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/kernel.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/parser.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/test_kernel.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/__pycache__/test_parser.cpython-34.pyc
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/constants.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/kernel.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/parser.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/test_kernel.py
      /e2e/venv/ipython3-venv/lib/python3.4/site-packages/redis_kernel/test_parser.py

**Comment by hari-allamraju** [comment]
That file will be in your home directory under ~/.ipython/kernels/redis_kernel

It's not removed with an uninstall - it's overwritten when you do an installation

**Comment by marmalodak** [comment]
Ah, yes, there it is, thank you.
However, I set `IPYTHONDIR` to `/e2e/...` -- should it be placed in my `$IPYTHONDIR`?

**Comment by hari-allamraju** [comment]
Yes you can move it to $IPYTHONDIR/kernels/redis_kernel

**Comment by marmalodak** [comment]
I guess I'm asking whether it is hard-coded.  If the environment variable `IPYTHONDIR` exists, use it instead of `~/.ipython`.

**Comment by hari-allamraju** [comment]
yes that's correct; I just tested it to be sure by pointing IPYTHONDIR to /tmp and when I installed redis-kernel the json was created under /tmp/kernels/redis

**Comment by marmalodak** [comment]
I can make the redis kernel start up in an ipython virtual environment, but not in a jupyter virtual environment.  Do I need to perform an extra step?

**Comment by hari-allamraju** [comment]
I haven't tested the kernel with a Jupyter virtualenv yet - can you create another issue for this? I will try to address it over the weekend

Also did this work before and break after my last fix?

**Comment by marmalodak** [comment]
I'm not sure I understand your question.  I had not tried the redis kernel until I first filed this issue, so I don't know when it first broke.
